const NY = [
	"Accord",
	"Addison",
	"Adirondack",
	"Afton",
	"Airmont",
	"Akron",
	"Akwesasne",
	"Albany",
	"Albertson",
	"Albion",
	"Alden",
	"Alexandria Bay",
	"Alfred",
	"Allegany",
	"Altamont",
	"Amagansett",
	"Amawalk",
	"Amenia",
	"Amherst",
	"Amity Harbor",
	"Amityville",
	"Amsterdam",
	"Andes",
	"Andover",
	"Angola",
	"Annandale On Hudson",
	"Apalachin",
	"Apo Ae",
	"Arcade",
	"Ardsley",
	"Ardsley On Hudson",
	"Armonk",
	"Arverne",
	"Ashland",
	"Astoria",
	"Atlantic Beach",
	"Attica",
	"Au Sable Forks",
	"Auburn",
	"Aurora",
	"Averill Park",
	"Avon",
	"Babylon",
	"Bainbridge",
	"Baldwin",
	"Baldwin Harbor",
	"Baldwinsville",
	"Ballston Lake",
	"Ballston Spa",
	"Bardonia",
	"Barker",
	"Barneveld",
	"Batavia",
	"Bath",
	"Bay Shore",
	"Bayport",
	"Bayshore",
	"Bayside",
	"Bayside Hills",
	"Bayville",
	"Beacon",
	"Beaver Falls",
	"Bedford",
	"Bedford Corners",
	"Bedford Hills",
	"Beechhurst",
	"Belle Harbor",
	"Belle Terre",
	"Bellerose",
	"Bellerose Manor",
	"Bellerose Village",
	"Bellmore",
	"Bellport",
	"Belmont",
	"Bemus Point",
	"Bergen",
	"Berkshire",
	"Berne",
	"Bethel",
	"Bethpage",
	"Big Flats",
	"Binghamton",
	"Bklyn",
	"Blasdell",
	"Blauvelt",
	"Bloomfield",
	"Bloomingburg",
	"Blue Point",
	"Bluff Point",
	"Bohemia",
	"Boiceville",
	"Bolivar",
	"Bolton Landing",
	"Boonville",
	"Bowmansville",
	"Brasher Falls",
	"Breezy Point",
	"Brentwood",
	"Brewerton",
	"Brewster",
	"Briarcliff",
	"Briarcliff Manor",
	"Briarwood",
	"Bridgehampton",
	"Bridgeport",
	"Brighton",
	"Brightwaters",
	"Broad Channel",
	"Broadalbin",
	"Brockport",
	"Brocton",
	"Bronx",
	"Bronxville",
	"Brookhaven",
	"Brooklyn",
	"Brookville",
	"Buffalo",
	"Burnt Hills",
	"Burt",
	"Cairo",
	"Caledonia",
	"Callicoon",
	"Calverton",
	"Cambria Heights",
	"Cambridge",
	"Camden",
	"Camillus",
	"Campbell Hall",
	"Canaan",
	"Canajoharie",
	"Canandaigua",
	"Canastota",
	"Candor",
	"Canton",
	"Carle Place",
	"Carmel",
	"Carthage",
	"Castile",
	"Castle Point",
	"Castleton",
	"Castleton On Hudson",
	"Cato",
	"Catskill",
	"Cazenovia",
	"Cedarhurst",
	"Center Moriches",
	"Centereach",
	"Centerport",
	"Central Islip",
	"Central Nyack",
	"Central Square",
	"Central Valley",
	"Champlain",
	"Chappaqua",
	"Charlton",
	"Chateaugay",
	"Chatham",
	"Chautauqua",
	"Cheektowaga",
	"Cherry Valley",
	"Chester",
	"Chestertown",
	"Chestnut Ridge",
	"Chittenango",
	"Cicero",
	"Cincinnatus",
	"Clarence",
	"Clarence Center",
	"Clay",
	"Clayton",
	"Clifton Park",
	"Clifton Springs",
	"Clinton",
	"Clinton Corners",
	"Clyde",
	"Cobleskill",
	"Cohocton",
	"Cohoes",
	"Cold Spring",
	"Cold Spring Harbor",
	"College Point",
	"Colonie",
	"Columbus",
	"Commack",
	"Congers",
	"Cooperstown",
	"Copake",
	"Copiague",
	"Coram",
	"Corfu",
	"Corinth",
	"Corning",
	"Cornwall",
	"Cornwall On Hudson",
	"Corona",
	"Cortland",
	"Cortlandt Manor",
	"Coxsackie",
	"Cropseyville",
	"Cross River",
	"Croton On Hudson",
	"Crown Point",
	"Cuba",
	"Cutchogue",
	"Dannemora",
	"Dansville",
	"De Kalb Junction",
	"De Witt",
	"Deansboro",
	"Deer Park",
	"Deerfield",
	"Delanson",
	"Delevan",
	"Delhi",
	"Delmar",
	"Depew",
	"Deposit",
	"Derby",
	"Dewitt",
	"Dewittville",
	"Dix Hills",
	"Dobbs Ferry",
	"Dolgeville",
	"Doughkeepsie",
	"Douglaston",
	"Dover Plains",
	"Downsville",
	"Dresden",
	"Dryden",
	"Duanesburg",
	"Dundee",
	"Dunkirk",
	"East Amherst",
	"East Atlantic Beach",
	"East Aurora",
	"East Berne",
	"East Elmhurst",
	"East Greenbush",
	"East Hampton",
	"East Hills",
	"East Islip",
	"East Meadow",
	"East Meredith",
	"East Moriches",
	"East Northport",
	"East Norwich",
	"East Patchogue",
	"East Rochester",
	"East Rockaway",
	"East Setauket",
	"East Syracuse",
	"East Williston",
	"East Yaphank",
	"Eastchester",
	"Eastport",
	"Eden",
	"Edgemere",
	"Edmeston",
	"Eggertsville",
	"Elbridge",
	"Elizabethtown",
	"Elizaville",
	"Elka Park",
	"Ellenburg",
	"Ellenburg Depot",
	"Ellenville",
	"Ellicottville",
	"Elma",
	"Elmhurst",
	"Elmira",
	"Elmont",
	"Elmsford",
	"Endicott",
	"Endwell",
	"Evans Mills",
	"Fabius",
	"Fairport",
	"Fallsburg",
	"Far Rockaway",
	"Farmingdale",
	"Farmington",
	"Farmingville",
	"Fayetteville",
	"Ferndale",
	"Feura Bush",
	"Fishkill",
	"Flanders",
	"Fleetwood",
	"Floral Park",
	"Florida",
	"Flushing",
	"Fonda",
	"Forest Hills",
	"Fort Drum",
	"Fort Edward",
	"Fort Montgomery",
	"Frankfort",
	"Franklin Square",
	"Franklinville",
	"Fredonia",
	"Freeport",
	"Freeville",
	"Fresh Meadows",
	"Fulton",
	"Galway",
	"Gansevoort",
	"Garden City",
	"Garden City Park",
	"Gardiner",
	"Garnerville",
	"Garrison",
	"Gates",
	"Geneseo",
	"Geneva",
	"Germantown",
	"Gerry",
	"Getzville",
	"Ghent",
	"Gilboa",
	"Glen Cove",
	"Glen Head",
	"Glen Oaks",
	"Glen Park",
	"Glendale",
	"Glenmont",
	"Glens Falls",
	"Glenville",
	"Gloversville",
	"Goldens Bridge",
	"Goshen",
	"Gouverneur",
	"Gowanda",
	"Grand Island",
	"Granville",
	"Great Neck",
	"Great River",
	"Greece",
	"Green Island",
	"Greene",
	"Greenfield Center",
	"Greenfield Park",
	"Greenlawn",
	"Greenport",
	"Greenvale",
	"Greenville",
	"Greenwich",
	"Groton",
	"Guilderland",
	"Hadley",
	"Halesite",
	"Halfmoon",
	"Hamburg",
	"Hamilton",
	"Hamlin",
	"Hammond",
	"Hammondsport",
	"Hampton Bays",
	"Hancock",
	"Harriman",
	"Harris",
	"Harrison",
	"Hartsdale",
	"Hartwick",
	"Hastings On Hudson",
	"Hauppauge",
	"Haverstraw",
	"Hawthorne",
	"Hempstead",
	"Henrietta",
	"Hensonville",
	"Herkimer",
	"Hewlett",
	"Hewlett Harbor",
	"Hicksville",
	"High Falls",
	"Highland",
	"Highland Falls",
	"Highland Mills",
	"Hillsdale",
	"Hilton",
	"Hogansburg",
	"Holbrook",
	"Holland",
	"Hollis",
	"Hollis Hills",
	"Holmes",
	"Holtsville",
	"Homer",
	"Honeoye",
	"Honeoye Falls",
	"Hoosick Falls",
	"Hopewell",
	"Hopewell Junction",
	"Hornell",
	"Horseheads",
	"Houghton",
	"Howard Beach",
	"Howes Cave",
	"Hudson",
	"Hudson Falls",
	"Huntington",
	"Huntington Bay",
	"Huntington Station",
	"Hurley",
	"Hyde Park",
	"Ilion",
	"Indian Lake",
	"Interlaken",
	"Inwood",
	"Irondequoit",
	"Irving",
	"Irvington",
	"Island Park",
	"Islandia",
	"Islip",
	"Islip Terrace",
	"Ithaca",
	"Jackson Heights",
	"Jamaica",
	"Jamaica Estates",
	"Jamesport",
	"Jamestown",
	"Jamesville",
	"Jefferson Valley",
	"Jeffersonville",
	"Jericho",
	"Johnson City",
	"Johnstown",
	"Jordan",
	"Katonah",
	"Keeseville",
	"Kendall",
	"Kenmore",
	"Kerhonkson",
	"Kew Gardens",
	"Kew Gardens Hills",
	"Kiamesha Lake",
	"Kill Buck",
	"Kinderhook",
	"Kings Park",
	"Kings Point",
	"Kingston",
	"Kirkville",
	"La Fayette",
	"La Grange",
	"Lackawanna",
	"Lagrangeville",
	"Lake Grove",
	"Lake Katrine",
	"Lake Luzerne",
	"Lake Placid",
	"Lake Ronkonkoma",
	"Lake Success",
	"Lakeville",
	"Lakewood",
	"Lancaster",
	"Larchmont",
	"Latham",
	"Laurelton",
	"Lawrence",
	"Le Roy",
	"Leroy",
	"Levittown",
	"Lewisboro",
	"Lewiston",
	"Lexington",
	"Liberty",
	"Lido Beach",
	"Lima",
	"Lindenhurst",
	"Lisle",
	"Little Falls",
	"Little Neck",
	"Liverpool",
	"Livingston",
	"Livingston Manor",
	"Livonia",
	"Lloyd Harbor",
	"Lockport",
	"Locust Valley",
	"Long Beach",
	"Long Island City",
	"Long Lake",
	"Loudonville",
	"Lowville",
	"Lynbrook",
	"Lyndonville",
	"Lyons",
	"Lyons Falls",
	"Macedon",
	"Madrid",
	"Mahopac",
	"Maine",
	"Malone",
	"Malta",
	"Malverne",
	"Mamaroneck",
	"Manhasset",
	"Manhasset Hills",
	"Manhattan",
	"Manlius",
	"Manorville",
	"Marathon",
	"Marcellus",
	"Marcy",
	"Margaretville",
	"Marion",
	"Marlboro",
	"Maryland",
	"Maspeth",
	"Massapequa",
	"Massapequa Park",
	"Massena",
	"Mastic",
	"Mattituck",
	"Mattydale",
	"Maybrook",
	"Mayville",
	"Mechanicville",
	"Medford",
	"Medina",
	"Melville",
	"Menands",
	"Mendon",
	"Merrick",
	"Mexico",
	"Mid Island",
	"Middle Island",
	"Middle Village",
	"Middleburgh",
	"Middleport",
	"Middletown",
	"Milford",
	"Millbrook",
	"Miller Place",
	"Millwood",
	"Milton",
	"Mineola",
	"Modena",
	"Mohawk",
	"Mohegan Lake",
	"Monroe",
	"Monsey",
	"Montauk",
	"Montebello",
	"Montgomery",
	"Monticello",
	"Montour Falls",
	"Montrose",
	"Moravia",
	"Moriches",
	"Morris",
	"Morrisonville",
	"Morrisville",
	"Mount Kisco",
	"Mount Morris",
	"Mount Sinai",
	"Mount Upton",
	"Mount Vernon",
	"Mountainville",
	"Munnsville",
	"Muttontown",
	"N Syracuse",
	"N Tonawanda",
	"Nanuet",
	"Napanoch",
	"Naples",
	"Natural Bridge",
	"Nedrow",
	"Neponsit",
	"Nesconset",
	"New City",
	"New Hampton",
	"New Hartfd",
	"New Hartford",
	"New Hyde Park",
	"New Lebanon",
	"New Paltz",
	"New Rochelle",
	"New Square",
	"New Windsor",
	"New York",
	"New York City",
	"New York Mills",
	"Newark",
	"Newark Valley",
	"Newburgh",
	"Newfane",
	"Newport",
	"Nf",
	"Niagara Falls",
	"Niskayuna",
	"Nontauk",
	"North Babylon",
	"North Baldwin",
	"North Bangor",
	"North Bellmore",
	"North Chili",
	"North Creek",
	"North Hills",
	"North Massapequa",
	"North Merrick",
	"North New Hyde Park",
	"North Salem",
	"North Syracuse",
	"North Tarrytown",
	"North Tonawanda",
	"North Valley Stream",
	"North White Plains",
	"North Woodmere",
	"Northport",
	"Northville",
	"Norwich",
	"Nunda",
	"Nyack",
	"Oak Beach",
	"Oakdale",
	"Oakfield",
	"Oakland Gardens",
	"Oceanside",
	"Ogdensburg",
	"Old Bethpage",
	"Old Brookville",
	"Old Forge",
	"Old Westbury",
	"Olean",
	"Oneida",
	"Oneonta",
	"Ontario",
	"Orangeburg",
	"Orchard Park",
	"Oriskany",
	"Oriskany Falls",
	"Ossining",
	"Oswego",
	"Otego",
	"Ovid",
	"Owego",
	"Oxford",
	"Oyster Bay",
	"Ozone Park",
	"Painted Post",
	"Palisades",
	"Palmyra",
	"Parksville",
	"Patchogue",
	"Patterson",
	"Pawling",
	"Pearl River",
	"Peconic",
	"Peekskill",
	"Pelham",
	"Pelham Manor",
	"Penfield",
	"Penn Yan",
	"Perry",
	"Perth",
	"Peru",
	"Phelps",
	"Phoenix",
	"Piermont",
	"Pine Bush",
	"Pine City",
	"Pittsford",
	"Plainview",
	"Plattsburgh",
	"Pleasant Valley",
	"Pleasantville",
	"Point Lookout",
	"Pomona",
	"Port Byron",
	"Port Chester",
	"Port Crane",
	"Port Ewen",
	"Port Jefferson",
	"Port Jervis",
	"Port Washington",
	"Potsdam",
	"Poughkeepsie",
	"Poughquag",
	"Pound Ridge",
	"Prattsville",
	"Pulaski",
	"Purchase",
	"Putnam Valley",
	"Queens Village",
	"Queensbury",
	"Quogue",
	"Randolph",
	"Ransomville",
	"Ravena",
	"Red Hook",
	"Rego Park",
	"Remsenburg",
	"Rensselaer",
	"Rexford",
	"Rhinebeck",
	"Richfield Springs",
	"Richford",
	"Richmond Hill",
	"Ridge",
	"Ridgewood",
	"Rifton",
	"Riverdale",
	"Riverhead",
	"Rochdale",
	"Rochester",
	"Rock Hill",
	"Rock Stream",
	"Rockaway Beach",
	"Rockaway Park",
	"Rockaway Point",
	"Rockville Center",
	"Rockville Centre",
	"Rocky Point",
	"Rome",
	"Romulus",
	"Ronkonkoma",
	"Roosevelt",
	"Roosevelt Island",
	"Rosedale",
	"Rosendale",
	"Roslyn",
	"Roslyn Heights",
	"Roxbury",
	"Rushville",
	"Rye",
	"Rye Brook",
	"Sackets Harbor",
	"Sag Harbor",
	"Saint Albans",
	"Saint James",
	"Saint Johnsville",
	"Salamanca",
	"Salem",
	"Salt Point",
	"Sanborn",
	"Sands Point",
	"Sandy Creek",
	"Saranac",
	"Saranac Lake",
	"Saratoga Springs",
	"Saugerties",
	"Sauquoit",
	"Sayville",
	"Scarsdale",
	"Schdy",
	"Schenectady",
	"Schoharie",
	"Schroon Lake",
	"Schuylerville",
	"Scipio Center",
	"Scotia",
	"Scottsville",
	"Sea Cliff",
	"Seaford",
	"Selden",
	"Selkirk",
	"Seneca Falls",
	"Setauket",
	"Sharon Springs",
	"Shelter Island",
	"Sherburne",
	"Sherman",
	"Sherrill",
	"Shirley",
	"Shoreham",
	"Shortsville",
	"Shrub Oak",
	"Si",
	"Sidney",
	"Silver Creek",
	"Skaneateles",
	"Slate Hill",
	"Sleepy Hollow",
	"Slingerlands",
	"Sloatsburg",
	"Smithtown",
	"Snyder",
	"Sodus",
	"Solvay",
	"Somers",
	"South Fallsburg",
	"South Floral Park",
	"South Glens Falls",
	"South Haven",
	"South Huntington",
	"South Kortright",
	"South Ozone Park",
	"South Richmond Hill",
	"South Salem",
	"South Setauket",
	"Southampton",
	"Southold",
	"Sparkill",
	"Sparrow Bush",
	"Spencerport",
	"Spring Valley",
	"Springfield Gardens",
	"Springville",
	"Stamford",
	"Stanfordville",
	"Star Lake",
	"Staten Island",
	"Stephentown",
	"Stillwater",
	"Stone Ridge",
	"Stony Brook",
	"Stony Point",
	"Stonybrook",
	"Stormville",
	"Suffern",
	"Sunnyside",
	"Syosset",
	"Syracuse",
	"Tannersville",
	"Tappan",
	"Tarrytown",
	"The Bronx, New York",
	"Thiells",
	"Thomaston",
	"Thornwood",
	"Ticonderoga",
	"Tivoli",
	"Tomkins Cove",
	"Tonawanda",
	"Troy",
	"Trumansburg",
	"Tuckahoe",
	"Tully",
	"Tupper Lake",
	"Tuxedo Park",
	"Ulster Park",
	"Unadilla",
	"Union Springs",
	"Uniondale",
	"Upton",
	"Utica",
	"Vails Gate",
	"Valatie",
	"Valhalla",
	"Valley Cottage",
	"Valley Stream",
	"Vernon",
	"Verona",
	"Vestal",
	"Victor",
	"Voorheesville",
	"Waccabuc",
	"Wading River",
	"Wainscott",
	"Walden",
	"Wallkill",
	"Walton",
	"Wampsville",
	"Wantagh",
	"Wappingers Falls",
	"Warrensburg",
	"Warsaw",
	"Warwick",
	"Washingtonville",
	"Wassaic",
	"Water Mill",
	"Waterford",
	"Waterloo",
	"Watertown",
	"Waterville",
	"Watervliet",
	"Watkins Glen",
	"Waverly",
	"Wawarsing",
	"Wayland",
	"Webster",
	"Wellesley Island",
	"Wellsville",
	"Wesley Hills",
	"West Amherst",
	"West Babylon",
	"West Brentwood",
	"West Chazy",
	"West Coxsackie",
	"West Harrison",
	"West Haverstraw",
	"West Hempstead",
	"West Henrietta",
	"West Hurley",
	"West Islip",
	"West Nyack",
	"West Point",
	"West Sayville",
	"West Seneca",
	"West Shokan",
	"West Valley",
	"West Winfield",
	"Westbury",
	"Westernville",
	"Westfield",
	"Westhampton",
	"Westhampton Beach",
	"Westmoreland",
	"Westport",
	"Westtown",
	"Wheatley Heights",
	"White Lake",
	"White Plains",
	"Whitehall",
	"Whitesboro",
	"Whitestone",
	"Whitney Point",
	"Willard",
	"Williamson",
	"Williamsville",
	"Williston Park",
	"Willsboro",
	"Wilson",
	"Wilton",
	"Windsor",
	"Wolcott",
	"Woodbury",
	"Woodhaven",
	"Woodmere",
	"Woodside",
	"Woodstock",
	"Worcester",
	"Wyandanch",
	"Wynantskill",
	"Yaphank",
	"Yonkers",
	"Yorktown Heights",
	"Youngstown", ]

export {
	NY
}

