const Specialty = [
	"Allergy & Immunology",
	"Anesthesiology",
	"Cardiology",
	"Clinical Genetics",
	"Colon & Rectal Surgery",
	"Dentistry",
	"Dermatology",
	"Emergency Medicine",
	"Endocrinology, Diabetes & Metabolism",
	"Endodontics",
	"Family Medicine",
	"Family Nurse Practitioner",
	"Gastroenterology",
	"General Surgery",
	"Geriatric Medicine",
	"Geriatric Nurse Practitioner",
	"Hematology",
	"Infectious Disease",
	"Internal Medicine",
	"Internal Medicine/Pediatrics",
	"Neonatal Nurse Practitioner",
	"Neonatal-Perinatal Medicine",
	"Nephrology",
	"Neurology",
	"Neurosurgery",
	"Nuclear Medicine",
	"Nurse Practitioner",
	"Obstetrics & Gynecology",
	"Occupational Medicine",
	"Oncology",
	"Ophthalmology",
	"Oral & Maxillofacial Surgery",
	"Orthopedic Surgery",
	"Orthopedics",
	"Other or Unknown Specialty",
	"Otolaryngology (ENT)",
	"Pathology",
	"Pediatric Cardiology",
	"Pediatric Emergency Medicine",
	"Pediatric Endocrinology",
	"Pediatric Gastroenterology",
	"Pediatric Hematology-Oncology",
	"Pediatric Infectious Disease",
	"Pediatric Nephrology",
	"Pediatric Neurology",
	"Pediatric Nurse Practitioner",
	"Pediatric Pulmonology",
	"Pediatric Rheumatology",
	"Pediatrics",
	"Physical Medicine & Rehabilitation",
	"Physician Assistant",
	"Plastic Surgery",
	"Psychiatry",
	"Public Health & Preventive Med",
	"Pulmonology",
	"Radiation Oncology",
	"Radiology",
	"Research Physician",
	"Resident Physician",
	"Rheumatology",
	"Thoracic Surgery",
	"Urology",
	"Vascular Surgery",
	"Women's Health Nurse Practitioner",
]

export {
	Specialty
}
